//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeogigModule.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pete")]
        public string UserNameSetting {
            get {
                return ((string)(this["UserNameSetting"]));
            }
            set {
                this["UserNameSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pete@example.com")]
        public string UserEmailSetting {
            get {
                return ((string)(this["UserEmailSetting"]));
            }
            set {
                this["UserEmailSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"url\": \"http://localhost:8182\", \"title\": \"local\"}]")]
        public string RepositoriesSetting {
            get {
                return ((string)(this["RepositoriesSetting"]));
            }
            set {
                this["RepositoriesSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[{\"repoUrl\": \"http://localhost:8182/repos/repo/\", \"source\": \"c:\\\\mapdata\\\\geogig\\" +
            "\\qgis_repo_data\\\\local\\\\repo\\\\citytown.gpkg|layername=citytown\", \"layername\": \"c" +
            "itytown\", \"geopkg\": \"c:\\\\mapdata\\\\geogig\\\\qgis_repo_data\\\\local\\\\repo\\\\citytown." +
            "gpkg\"}]")]
        public string TrackedLayersSetting {
            get {
                return ((string)(this["TrackedLayersSetting"]));
            }
            set {
                this["TrackedLayersSetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Mapdata\\geogig\\qgis_repo_data")]
        public string BaseDataFolderSetting {
            get {
                return ((string)(this["BaseDataFolderSetting"]));
            }
            set {
                this["BaseDataFolderSetting"] = value;
            }
        }
    }
}
